/**
 * Generated by scripts/gen-blur.mjs. Do not edit by hand.
 *
 * A 14px preview of each photograph, inlined as a data URI. next/image shows
 * it stretched and blurred until the real file decodes, so pictures resolve
 * into place instead of appearing all at once. Most visible on exactly the
 * slow connections this page is built for.
 */

export const BLUR: Record<string, string> = {
  "/img/front.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoNAA4AAwBWJZgC7AEQXFcBywAA9HbnzsZpAlDWSLb6JPOBIzywmUqjJYzYjKupgG2U8Rg7VzHWS/KIUOlut3ackytaJEJfTYo9tmJSECOgIIC7kBMTgAAA",
  "/img/machines-2.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoOAAoAAwBWJYwCdACkofId7ADKsnTu4pHb9lmPULvRRiy5IJ3DwytLbXtEPMc/VMXW4yhDd2vwp7sms/TLXrR1AtWdR9TLgEt44sbUAAA=",
  "/img/machines.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoOAAoAAwBWJYwCdAEJTaX6YADhttQb48N7k/7PTAlROioZzBtLXXMYCigHYjN34sFkFTRQMqjAMmIzwfu6FunVcb/MAA==",
  "/img/side1.webp": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoOAAsAAwBWJZwCdAEPhx1YaHQA/trMvX1iAiK9Dl0B1dlaU5pwfjtM1dBT9GlJ9yNJfFg0gO1dyjCQgA6ZXcbmfXaVr+AA",
  "/img/side2.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoOAAkAAwBWJZwAAvc7mxILgAD+0j4iozz6iEPh7CVmYSkKa2gDB6lnemjsHLLC+NV4wsjA5AZXBih31wAAAA==",
  "/img/step-prescription.webp": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoOAAoAAwBWJQBOgCBUtgxQeHmAAP7CRk4bBZbmmC9Md29sAUaH6y43ARNbMyq5tpn95JwSl93jGyvdQrmG/C8etc6bRTakuix4VjKwHPOiSSkAAAA=",
  "/img/step-sample.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoOAAoAAwBWJQBOgBur3Tj3YQAA/u0s0Mr9P3b+Z9HF8l7n9b4lqyeC6x4/872PLjD10q+Ssv1k8vnvdMKKM9b8gLkbyScD+5LeV+7p2xXwsE2WVxklx8gA",
};

/** Undefined for anything without a preview, which next/image treats as "no placeholder". */
export const blurFor = (src: string) => BLUR[src.replace(/^.*(\/img\/)/, "$1")];
