/**
 * Gives the generated link-preview card a file extension.
 *
 * app/opengraph-image.tsx renders the card, and under `output: "export"`
 * Next writes it to `out/opengraph-image` — with no extension — and points
 * the meta tags at `/opengraph-image?<hash>`.
 *
 * That is fine on a server that sets Content-Type from a route table. It is
 * not fine on GitHub Pages, which infers the type from the file extension
 * alone: an extensionless file is served as a generic download, and
 * WhatsApp and Facebook will not render an og:image that arrives without an
 * image Content-Type. The card would silently fail on the exact surface it
 * exists for.
 *
 * So the file is moved to out/img/og.png and the tags are repointed at it.
 * Wired into `npm run build`, which means the deploy workflow runs it too.
 *
 * It is deliberately loud on failure. A silently skipped fix-up would ship
 * a broken preview that nobody notices until a patient sees a grey box in a
 * family group chat.
 */

import fs from "node:fs";
import path from "node:path";

const OUT = "out";
const SRC = path.join(OUT, "opengraph-image");
const DEST_REL = "/img/og.png";
const DEST = path.join(OUT, "img", "og.png");

if (!fs.existsSync(OUT)) {
  console.log("fix-og: no out/ directory — not a static export build, skipping");
  process.exit(0);
}

if (!fs.existsSync(SRC)) {
  console.error(
    "fix-og: expected " +
      SRC +
      " to exist.\n" +
      "The card is generated by app/opengraph-image.tsx. If that file was " +
      "removed, remove this script from the build too.",
  );
  process.exit(1);
}

const png = fs.readFileSync(SRC);
if (png.subarray(1, 4).toString() !== "PNG") {
  console.error("fix-og: " + SRC + " is not a PNG");
  process.exit(1);
}

fs.mkdirSync(path.dirname(DEST), { recursive: true });
fs.writeFileSync(DEST, png);
fs.rmSync(SRC);

/* Repoint every tag that referenced the extensionless route. The href
   carries a cache-busting query, so match up to the closing quote. */
let rewritten = 0;
for (const file of fs.readdirSync(OUT)) {
  if (!file.endsWith(".html")) continue;
  const full = path.join(OUT, file);
  const before = fs.readFileSync(full, "utf8");
  const after = before.replace(
    /(content=")([^"]*?)\/opengraph-image(\?[^"]*)?(")/g,
    (_m, open, origin, _q, close) => `${open}${origin}${DEST_REL}${close}`,
  );
  if (after !== before) {
    fs.writeFileSync(full, after, "utf8");
    rewritten++;
  }
}

if (rewritten === 0) {
  console.error("fix-og: card was moved but no meta tag referenced it");
  process.exit(1);
}

console.log(
  `fix-og: ${DEST} (${Math.round(png.length / 1024)} KB), ` +
    `${rewritten} page(s) repointed at ${DEST_REL}`,
);
