/**
 * Generates lib/blur.ts — tiny inline previews for every photograph.
 *
 * Run when an image in public/img changes:
 *
 *   npx --yes sharp-cli --version >/dev/null   # sharp is not a dependency
 *   node scripts/gen-blur.mjs
 *
 * sharp is deliberately not in package.json. This runs perhaps twice a year,
 * and a native image binary in the install graph is a poor trade for that.
 * Fetch it with npx when you need it; the generated file is committed, so a
 * normal build never touches any of this.
 *
 * The previews are 14px on the long edge and land at roughly 300 bytes each
 * as base64. They are inlined into the HTML, so they cost one round trip of
 * nothing and are on screen before the real file has finished negotiating.
 */

import { createRequire } from "node:module";
import fs from "node:fs/promises";
import path from "node:path";

const require = createRequire(import.meta.url);

let sharp;
try {
  sharp = require("sharp");
} catch {
  console.error(
    "sharp not found. Install it just for this run:\n" +
      "  npm i --no-save sharp && node scripts/gen-blur.mjs",
  );
  process.exit(1);
}

const IMG_DIR = path.join(process.cwd(), "public", "img");
const OUT = path.join(process.cwd(), "lib", "blur.ts");

/* Only photographs. Logos and icons have flat colour and hard edges — a
   blurred preview of those reads as a smudge, not as the image arriving. */
const SKIP = /^(favicon|logo-mark|og)[-.]/;

const files = (await fs.readdir(IMG_DIR))
  .filter((f) => /\.(webp|jpe?g|png)$/i.test(f))
  .filter((f) => !SKIP.test(f))
  .sort();

const entries = [];
for (const file of files) {
  const buf = await sharp(path.join(IMG_DIR, file))
    .resize(14, 14, { fit: "inside" })
    .webp({ quality: 42 })
    .toBuffer();
  entries.push([`/img/${file}`, `data:image/webp;base64,${buf.toString("base64")}`]);
  console.log(`  ${file} -> ${buf.length} bytes`);
}

const body = entries
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join("\n");

await fs.writeFile(
  OUT,
  `/**
 * Generated by scripts/gen-blur.mjs. Do not edit by hand.
 *
 * A 14px preview of each photograph, inlined as a data URI. next/image shows
 * it stretched and blurred until the real file decodes, so pictures resolve
 * into place instead of appearing all at once. Most visible on exactly the
 * slow connections this page is built for.
 */

export const BLUR: Record<string, string> = {
${body}
};

/** Undefined for anything without a preview, which next/image treats as "no placeholder". */
export const blurFor = (src: string) => BLUR[src.replace(/^.*(\\/img\\/)/, "$1")];
`,
  "utf8",
);

console.log(`\nwrote ${OUT} (${entries.length} previews)`);
